services:
  redis:
    image: redis
    networks:
      - webnet
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  postgres:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: social-media
  api:
    image: social-media-api
    ports:
      - "8080:8080"
    networks:
      - webnet
    environment:
      PORT: 8080
      DB_URL: postgres://postgres:postgres@postgres/social-media
      REDIS_URL: redis://redis:6379
  messenger:
    image: messenger
    ports:
      - "8081:8081"
    networks:
      - webnet
    environment:
      PORT: 8081
      DB_URL: postgres://postgres:postgres@postgres/social-media
      REDIS_URL: redis://redis:6379

networks:
  webnet:
